export class CadastroPaciente{
  constructor(){
    this.nome  = "";
    this.idade = "";
    this.sexo = "";
    this.estadoCivil = "";
    this.religiao = "";
    this.naturalidade = "";
    this.procedencia = "";
    this.leito = "";
    this.dataInternacao = "";
    this.registro = "";
    this.setorDeProcedencia = "";
    this.diagnosticoMedico = "";
    this.internacaoAnterior = "";
    this.cardiopatia = false;
    this.convulsao = false;
    this.asma = false;
    this.drogas = false;
    this.has = false;
    this.tabagismo = false;
    this.diabetesMellitus = false;
    this.alcoolismo = false;
    this.qtdeAntecedentes = 0;
    this.antecedentes = [];
    this.qtdeAlergias = 0;
    this.alergias = [];
    this.qtdeVacinas = 0;
    this.vacinas = [];
    this.alerta = false;
    this.letargico = false;
    this.obnubilado = false;
    this.torporoso = false;
    this.comatoso = false;
    this.glasgow = 0;
    this.glasgowOcular;
    this.glasgowVerbal;
    this.glasgowMotor;
    this.isocorica = false;
    this.anisocorica = false;
    this.miose = false;
    this.midriase = false;
    this.rfm = false;
    this.mmss ;
    this.preservada = false;
    this.paresia = false;
    this.plegia = false;
    this.parestesia = false;
    this.movimentosLentos = false;
    this.movimentosInvoluntarios = false;
    this.obsRespiracao = 0;
    this.respiracoes= [];
    this.espontanea = false;
    this.cateter = false;
    this.mascara = false;
    this.traqueostomia = false;
    this.o = "";
    this.sop = "";
    this.fr = "";
    this.dispneia = false;
    this.taquipneia = false;
    this.bradipneia = false;
    this.hiperventilacaoNeurogenica = false;
    this.apneustica = false;
    this.biot = false;
    this.cheyne = false;
    this.kussmaul = false;
    this.emSalvas = false;
    this.ventilacaoMecanica = false;
    this.modalidade = "";
    this.fiO2 = "";
    this.peep = "";
    this.spO2 = "";
    this.bilateralmente = false;
    this.diminuidos = false;
    this.roncos = false;
    this.sibilos = false;
    this.estertores = false;
    this.presencaoDeTosseNao = false;
    this.presencaoDeTosseSim = false;
    this.presencaoDeTosseSeca = false;
    this.presencaoDeTosseProdutiva = false;
    this.presencaoDeTosseExpectoracao = false;
    this.glasgowMenu = false;
    this.aspiracao ;
    this.aspiracaoQuantidade = "";
    this.aspiracaoCaracteristica = "";
    this.drenagemToracica ;
    this.drenagemToracicaDTE = false;
    this.drenagemToracicaDTD = false;
    this.drenagemToracicaQuantidade = "";
    this.drenagemToracicaCaracteristica = "";
    this.mamaOutros = "";
    this.mamaSemAltecacoes = false;
    this.mamaNodulos = false;
    this.mamaDor = false;
    this.mamaAssimetrica = false;
    this.avaliacaoCardiovascularFC = "";
    this.avaliacaoCardiovascularPA = "";
    this.avaliacaoCardiovascularPVC = "";
    this.avaliacaoCardiovascularPAM = "";
    this.pulsoRegular = false;
    this.pulsoIrregular = false;
    this.pulsoPalpavel = false;
    this.pulsoImpalpavel = false;
    this.pulsoCheio = false;
    this.pulsoFiliforme = false;
    this.presencaDeEdemaNao = false;
    this.presencaDeEdemaSim = false;
    this.presencaDeEdemaPes = false;
    this.presencaDeEdemaMMII = false;
    this.presencaDeEdemaMMSS = false;
    this.presencaDeEdemaAnasarca = false;
    this.turgidezDaPele ;
    this.eliminacaoUrinariaVolume = "";
    this.eliminacaoUrinariaEspontanea = false;
    this.eliminacaoUrinariaRetencao = false;
    this.eliminacaoUrinariaIncontinencia = false;
    this.eliminacaoUrinariaSVD = false;
    this.eliminacaoUrinariaDispositivoUrinario = false;
    this.caracteristicasDisuria = false;
    this.caracteristicasOliguria = false;
    this.caracteristicasAnuria = false;
    this.caracteristicasPoliuria = false;
    this.caracteristicasHematuria = false;
    this.caracteristicasOutros = "";
    this.tipoDeDieta = "";
    this.glicemia = "";
    this.apetite;
    this.viasDeAdministracaoOral = false;
    this.viasDeAdministracaoSNG = false;
    this.viasDeAdministracaoSNE = false;
    this.viasDeAdministracaoParenteral = false;
    this.viasDeAdministracaoOutros = "";
    this.presencaoDeNausea = false;
    this.presencaoDeVomitoQuantidade = "";
    this.presencaoDeVomitoCaracteristica = "";
    this.presencaoDeVomito = false;
    this.abdomePlano = false;
    this.abdomeGloboso = false;
    this.abdomeDistendido = false;
    this.abdomeDolorosoAPalpacao = false;
    this.abdomeOutros = "";
    this.rhaPresentes = false;
    this.rhaAusentes = false;
    this.rhaDiminuido = false;
    this.rhaAumentado = false;
    this.ostomia ;
    this.ostomiaLocal = "";
    this.ostomiaCaracteristica = "";
    this.eliminacaoIntestinal ;
    this.eliminacaoIntestinalFrequencia = "";
    this.eliminacaoIntestinalOutros = "";

  }
}
