export class CadastroPaciente{
  constructor(){
    this.nome  = "";
    this.idade = "";
    this.sexo = "";
    this.estadoCivil = "";
    this.religiao = "";
    this.naturalidade = "";
    this.procedencia = "";
    this.leito = "";
    this.dataInternacao = "";
    this.registro = "";
    this.setorDeProcedencia = "";
    this.diagnosticoMedico = "";
    this.internacaoAnterior = "";
    this.cardiopatia = false;
    this.convulsao = false;
    this.asma = false;
    this.drogas = false;
    this.has = false;
    this.tabagismo = false;
    this.diabetesMellitus = false;
    this.alcoolismo = false;
    this.alerta = false;
    this.letargico = false;
    this.obnubilado = false;
    this.torporoso = false;
    this.comatoso = false;
    this.glasgow = 0;
    this.qtdeOutros = 0;
    this.qtdeAlergias = 0;
    this.qtdeVacinas = 0;
    this.glasgowOcular;
    this.glasgowVerbal;
    this.glasgowMotor;
    this.isocorica = false;
    this.anisocorica = false;
    this.miose = false;
    this.midriase = false;
    this.rfm = false;
    this.mmss ;
    this.preservada = false;
    this.paresia = false;
    this.plegia = false;
    this.parestesia = false;
    this.movimentosLentos = false;
    this.movimentosInvoluntarios = false;
    this.obsRespiracao = 0;
    this.espontanea = false;
    this.cateter = false;
    this.mascara = false;
    this.traqueostomia = false;
    this.o = "";
    this.sop = "";
    this.fr = "";
    this.dispneia = false;
    this.taquipneia = false;
    this.bradipneia = false;
    this.hiperventilacaoNeurogenica = false;
    this.apneustica = false;
    this.biot = false;
    this.cheyne = false;
    this.kussmaul = false;
    this.emSalvas = false;
    this.ventilacaoMecanica = false;
    this.modalidade = "";
    this.fiO2 = "";
    this.peep = "";
    this.spO2 = "";
    this.bilateralmente = false;
    this.diminuidos = false;
    this.roncos = false;
    this.sibilos = false;
    this.estertores = false;
    this.presencaoDeTosseNao = false;
    this.presencaoDeTosseSim = false;
    this.presencaoDeTosseSeca = false;
    this.presencaoDeTosseProdutiva = false;
    this.presencaoDeTosseExpectoracao = false;

  }
}
